# ====================================
# COMP90024 Cluster and Cloud Computing
# Group 17 - Assignment 2
# Xunye Tian 1021181
# Kechen Zhao 957398
# Yuzhe Jie 1189869
# Qingyang Feng 980940
# Wentian Ding 1048673
# Last Updated: 2022-05-14
# Description: setup nginx web sever to handle http request
# ====================================

---

- name: Pull docker image of nginx
  become: yes
  community.docker.docker_image: 
    name: "nginx"
    source: pull

- name: Create and start a couchdb container
  become: yes
  community.docker.docker_container:
    name: "nginx{{ ansible_host }}"
    image: "nginx"
    state: started
    ports: 
      - 8080:80
    container_default_behavior: no_defaults