# ====================================
# COMP90024 Cluster and Cloud Computing
# Group 17 - Assignment 2
# Xunye Tian 1021181
# Kechen Zhao 957398
# Yuzhe Jie 1189869
# Qingyang Feng 980940
# Wentian Ding 1048673
# Last Updated: 2022-05-12
# Description: show all images
# ====================================

---
# Show all available Openstack images (just for demo, you don't need this task to create instance) 
- name: Retrieve all available Openstack images
  openstack.cloud.image_info:
  register: image_result

- name: Get image names and Ids
  ansible.builtin.set_fact:
    image_facts: "{{ image_facts|default([]) + [ {'name': item.name, 'id': item.id} ] }}"
  loop: '{{ image_result.openstack_image }}'
  when: item.name is defined

- name: Show images
  ansible.builtin.debug:
    msg: "Image name: {{ item.name }}; Image id: {{ item.id }}"
  loop: '{{ image_facts }}'
