# ====================================
# COMP90024 Cluster and Cloud Computing
# Group 17 - Assignment 2
# Xunye Tian 1021181
# Kechen Zhao 957398
# Yuzhe Jie 1189869
# Qingyang Feng 980940
# Wentian Ding 1048673
# Last Updated: 2022-05-12
# Description: setup environment
# ====================================

---
# Install dependencies on the host
- name: Install pip
  become: yes
  ansible.builtin.apt:
    name: ['python3-dev', 'python3-setuptools', 'python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update && sudo apt-get install python3-dev python3-setuptools python-pip

- name: Update pip
  ansible.builtin.pip:
    name: ['pip', 'openstacksdk']
    state: latest
# pip install --upgrade pip && pip install openstacksdk

- name: copy private key with chmod
  ansible.builtin.copy:
    src: ./ccc-group17.pem
    dest: ~/.ssh/ccc-group17.pem
    mode: 0600
